import type { User } from "@/types/user";

export const initialUsers: User[] = [
  {
    id: 1,
    name: "Ariana Gomez",
    email: "ariana.gomez@example.com",
    phone: "01234567890",
    dob: "1996-04-12",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    gender: "Female",
    bio: "Frontend developer passionate about crafting elegant UI experiences with React and Tailwind CSS.",
    designation: "Frontend Developer",
    skills: ["HTML", "CSS", "JavaScript", "React.js", "Tailwind CSS"],
  },
  {
    id: 2,
    name: "Rafiul Hasan",
    email: "rafiul.hasan@example.com",
    phone: "01234567891",
    dob: "1998-09-25",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    gender: "Male",
    bio: "Full Stack Developer who loves building scalable web applications using the MERN stack.",
    designation: "Full Stack Developer",
    skills: ["React.js", "Node.js", "Express.js", "MongoDB", "Redux"],
  },
  {
    id: 3,
    name: "Sophia Chen",
    email: "sophia.chen@example.com",
    phone: "01234567892",
    dob: "1995-07-18",
    image: "https://randomuser.me/api/portraits/women/32.jpg",
    gender: "Female",
    bio: "Backend engineer specializing in microservices architecture and cloud infrastructure.",
    designation: "Backend Developer",
    skills: ["Python", "Django", "Docker", "AWS", "PostgreSQL"],
  },
  {
    id: 4,
    name: "Marcus Johnson",
    email: "marcus.johnson@example.com",
    phone: "01234567893",
    dob: "1993-11-05",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    gender: "Male",
    bio: "DevOps engineer focused on automation, CI/CD pipelines, and infrastructure as code.",
    designation: "DevOps Engineer",
    skills: ["Kubernetes", "Terraform", "Jenkins", "Linux", "Bash"],
  },
  {
    id: 5,
    name: "Lena Schmidt",
    email: "lena.schmidt@example.com",
    phone: "01234567894",
    dob: "1997-02-28",
    image: "https://randomuser.me/api/portraits/women/78.jpg",
    gender: "Female",
    bio: "Mobile developer creating beautiful native iOS applications with Swift and SwiftUI.",
    designation: "iOS Developer",
    skills: ["Swift", "SwiftUI", "Objective-C", "Xcode", "Core Data"],
  },
  {
    id: 6,
    name: "David Kim",
    email: "david.kim@example.com",
    phone: "01234567895",
    dob: "1994-08-14",
    image: "https://randomuser.me/api/portraits/men/67.jpg",
    gender: "Male",
    bio: "Data scientist passionate about machine learning and extracting insights from complex datasets.",
    designation: "Data Scientist",
    skills: ["Python", "TensorFlow", "Pandas", "SQL", "Machine Learning"],
  },
  {
    id: 7,
    name: "Isabella Rossi",
    email: "isabella.rossi@example.com",
    phone: "01234567896",
    dob: "1999-01-22",
    image: "https://randomuser.me/api/portraits/women/51.jpg",
    gender: "Female",
    bio: "UX/UI designer focused on creating intuitive and accessible user experiences.",
    designation: "UX/UI Designer",
    skills: ["Figma", "Adobe XD", "User Research", "Wireframing", "Prototyping"],
  },
  {
    id: 8,
    name: "James Wilson",
    email: "james.wilson@example.com",
    phone: "01234567897",
    dob: "1992-12-30",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
    gender: "Male",
    bio: "Android developer building modern mobile applications with Kotlin and Jetpack Compose.",
    designation: "Android Developer",
    skills: ["Kotlin", "Java", "Android SDK", "Jetpack Compose", "Room DB"],
  },
  {
    id: 9,
    name: "Emma Thompson",
    email: "emma.thompson@example.com",
    phone: "01234567898",
    dob: "1996-06-08",
    image: "https://randomuser.me/api/portraits/women/89.jpg",
    gender: "Female",
    bio: "QA engineer ensuring software quality through automated testing and continuous integration.",
    designation: "QA Engineer",
    skills: ["Selenium", "Cypress", "Jest", "Test Automation", "JIRA"],
  },
  {
    id: 10,
    name: "Ahmed Hassan",
    email: "ahmed.hassan@example.com",
    phone: "01234567899",
    dob: "1991-03-17",
    image: "https://randomuser.me/api/portraits/men/56.jpg",
    gender: "Male",
    bio: "Database administrator optimizing performance and ensuring data integrity across systems.",
    designation: "Database Administrator",
    skills: ["SQL", "MySQL", "PostgreSQL", "MongoDB", "Database Design"],
  },
  {
    id: 11,
    name: "Olivia Parker",
    email: "olivia.parker@example.com",
    phone: "01234567900",
    dob: "1998-10-11",
    image: "https://randomuser.me/api/portraits/women/42.jpg",
    gender: "Female",
    bio: "Frontend developer specializing in Vue.js and creating responsive web applications.",
    designation: "Frontend Developer",
    skills: ["Vue.js", "JavaScript", "TypeScript", "Vuex", "SASS"],
  },
  {
    id: 12,
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    phone: "01234567901",
    dob: "1995-05-03",
    image: "https://randomuser.me/api/portraits/men/34.jpg",
    gender: "Male",
    bio: "Cloud architect designing scalable and secure cloud infrastructure solutions.",
    designation: "Cloud Architect",
    skills: ["AWS", "Azure", "GCP", "Terraform", "Cloud Security"],
  },
  {
    id: 13,
    name: "Maya Patel",
    email: "maya.patel@example.com",
    phone: "01234567902",
    dob: "1997-09-19",
    image: "https://randomuser.me/api/portraits/women/27.jpg",
    gender: "Female",
    bio: "Full stack developer with expertise in React and Node.js for building modern web apps.",
    designation: "Full Stack Developer",
    skills: ["React.js", "Node.js", "TypeScript", "GraphQL", "PostgreSQL"],
  },
  {
    id: 14,
    name: "Carlos Rodriguez",
    email: "carlos.rodriguez@example.com",
    phone: "01234567903",
    dob: "1994-04-25",
    image: "https://randomuser.me/api/portraits/men/78.jpg",
    gender: "Male",
    bio: "Backend developer focused on building RESTful APIs and microservices with Java.",
    designation: "Backend Developer",
    skills: ["Java", "Spring Boot", "Microservices", "REST APIs", "Hibernate"],
  },
  {
    id: 15,
    name: "Sarah Williams",
    email: "sarah.williams@example.com",
    phone: "01234567904",
    dob: "1999-07-14",
    image: "https://randomuser.me/api/portraits/women/63.jpg",
    gender: "Female",
    bio: "Product manager bridging the gap between technical teams and business stakeholders.",
    designation: "Product Manager",
    skills: ["Product Strategy", "Agile", "JIRA", "User Stories", "Roadmapping"],
  },
  {
    id: 16,
    name: "Kenji Tanaka",
    email: "kenji.tanaka@example.com",
    phone: "01234567905",
    dob: "1993-02-09",
    image: "https://randomuser.me/api/portraits/men/89.jpg",
    gender: "Male",
    bio: "Machine learning engineer developing and deploying AI models for real-world applications.",
    designation: "ML Engineer",
    skills: ["Python", "PyTorch", "Deep Learning", "Computer Vision", "MLOps"],
  },
  {
    id: 17,
    name: "Nadia Ali",
    email: "nadia.ali@example.com",
    phone: "01234567906",
    dob: "1996-11-27",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    gender: "Female",
    bio: "Security engineer passionate about cybersecurity and protecting digital assets.",
    designation: "Security Engineer",
    skills: ["Penetration Testing", "Network Security", "Cryptography", "OWASP", "SIEM"],
  },
  {
    id: 18,
    name: "Thomas Brown",
    email: "thomas.brown@example.com",
    phone: "01234567907",
    dob: "1992-08-06",
    image: "https://randomuser.me/api/portraits/men/41.jpg",
    gender: "Male",
    bio: "Technical lead guiding development teams and ensuring code quality and best practices.",
    designation: "Technical Lead",
    skills: ["Leadership", "System Design", "Code Review", "Mentoring", "Architecture"],
  },
  {
    id: 19,
    name: "Chloe Martin",
    email: "chloe.martin@example.com",
    phone: "01234567908",
    dob: "1998-12-15",
    image: "https://randomuser.me/api/portraits/women/74.jpg",
    gender: "Female",
    bio: "Software engineer with focus on scalable backend systems and database optimization.",
    designation: "Software Engineer",
    skills: ["Java", "Python", "SQL", "Redis", "System Design"],
  },
  {
    id: 20,
    name: "Mohammed Khan",
    email: "mohammed.khan@example.com",
    phone: "01234567909",
    dob: "1995-06-21",
    image: "https://randomuser.me/api/portraits/men/62.jpg",
    gender: "Male",
    bio: "Blockchain developer building decentralized applications and smart contracts.",
    designation: "Blockchain Developer",
    skills: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts", "DeFi"],
  }
];